kind: Service
apiVersion: v1
metadata:
  #Service name
  name: fulfillment-service
spec:
  selector:
    app: costco-202313
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
